// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Cyclone-Aurora","status":false,"description":"Basic lighting plugin\n\n<pluginName:CycloneAurora>","parameters":{}},
{"name":"Cyclone-Events","status":true,"description":"<pluginName:CycloneEvents>","parameters":{}},
{"name":"Cyclone-Map-Editor","status":false,"description":"Live Map Editor - v1.12.00\n\n<pluginName:CycloneMapEditor>","parameters":{"regionIcons":"","Status Bar":"","showMapId":"true","showTilesetId":"true","showPosition":"true","showCellTiles":"true","showRegionId":"true","showTag":"true","showCollision":"true","showLadder":"true","showBush":"true","showCounter":"true","showDamageFloor":"true","collisionStepCount":"1"}},
{"name":"Cyclone-Maps","status":true,"description":"Adds new features to game map\r\n\r\n<pluginName:CycloneMaps>","parameters":{"Map Change Event Id":"0","Change Tile Size":"","Tile Width":"32","Tile Height":"32","Tileset Path":"img/tilesets/32/","Map Settings":"","disableAutoShadows":"false","Overlay":"","enableOverlays":"false","disableTilemap":"false","Organized Folders":"false","Parallax Layer Filename":"par","Ground Layer Filename":"ground","Light Layer Filename":"light","Shadow Layer Filename":"shadow","Light Opacity":"185","Quick Start":"true","Fog Switch ID":"0","Light Switch ID":"0","Parallax Switch ID":"0","Shadow Switch ID":"0","Fog Z":"22","Light Z":"23","Parallax Z":"20","Shadow Z":"21","Ground Z":"1","Balloon Z":"7","Animations Z":"8","Regions":"","bushRegionId":"0","Region Movement":"","blockRegionId":"0","unblockRegionId":"0","blockPlayerRegionId":"0","unblockPlayerRegionId":"0","blockEventRegionId":"0","unblockEventRegionId":"0","Region Actions":"","commonEventRegions":"","namedRegions":"","regionNamesStay":"false"}},
{"name":"Cyclone-Movement","status":true,"description":"Adds new movement features to the game v1.01.01\n\n<pluginName:CycloneMovement>","parameters":{"stepCount":"2","collisionStepCount":"1","followerStepsBehind":"3","triggerAllEvents":"false","ignoreEmptyEvents":"true","autoLeaveVehicles":"false","diagonalPathfinding":"true","disableMouseMovement":"false","maxOffset":"0.75","sidestepEvents":"false"}},
{"name":"wasdKeyMZ","status":true,"description":"It is a plugin that corresponds to the wasd move.","parameters":{}},
{"name":"colyseus","status":true,"description":"","parameters":{}},
{"name":"Cyclone-Colyseus","status":true,"description":"<pluginName:CycloneColyseus>","parameters":{}},
{"name":"Cyclone-EventsMovement","status":true,"description":"Adds new movement features to the game v1.01.01\n\n<pluginName:CycloneEventsMovement>","parameters":{}},
{"name":"GGJ01","status":true,"description":"<pluginName:GGJ01>","parameters":{}}
];
